[package]
name = "dice-syntax"
version = "0.1.0"
authors = ["Josh Rodgers <bytemr@gmail.com>"]
edition = "2018"

[dependencies]
logos = "0.11"
id-arena = "2.2"
thiserror = "1"
unicode-width = "0.1"
dice-core = {path = "../dice-core"}
