[package]
authors = ["Josh Rodgers <bytemr@gmail.com>"]
edition = "2018"
name = "dice-syntax"
version = "0.1.0"

[dependencies]
dice-core = {path = "../dice-core"}
id-arena = "2.2"
logos = "0.12"
thiserror = "1"
unicode-width = "0.1"
