[package]
name = "dice-core"
version = "0.1.0"
authors = ["Josh Rodgers <bytemr@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4"] }
wyhash = "0.4"
num-derive = "0.3"
num-traits = "0.2"

dice-error = {path = "../dice-error"}