[package]
name = "dice-core"
version = "0.1.0"
authors = ["Josh Rodgers <bytemr@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
uuid = "0.8.1"
thiserror = "1.0"
anyhow = "1.0"

dice-error = {path = "../dice-error"}
dice-syntax = {path = "../dice-syntax"}