[package]
name = "dice-syntax2"
version = "0.1.0"
authors = ["Josh Rodgers <bytemr@gmail.com>"]
edition = "2018"

[dependencies]
logos = "0.11"
num-derive = "0.3"
num-traits = "0.2"
rowan = "0.10"
wyhash = "0.4"

[dev-dependencies]
expect-test = "1.0"