[package]
name = "dice-runtime"
version = "0.1.0"
authors = ["Josh Rodgers <bytemr@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
dice-core = {path = "../dice-core"}
dice-compiler = {path = "../dice-compiler"}